datakaveri/dx-acl-apd

- src/main/java/iudx/apd/acl/server/policy/CatalogueClient.java
- src/main/java/iudx/apd/acl/server/policy/CreatePolicy.java
- src/test/resources/IUDX-ACL-APD-APIs.postman_collection.json
- Resolved integration test failure by updating the expiryTime
- Resolved check style issues
> Resolve integration test failure

- docs/SETUP-and-Installation.md
- Added and trimmed unit test video with script
> Add unit test video

- README.md
Added both .mp4, .webm video tutorials in README.md to check if any of them are rendered in mobile screen
> Add video asset

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/new-feature.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- Added code of conduct by referencing [Opensource.com](https://opensource.com/code-of-conduct), [Python code of conduct](https://policies.python.org/python.org/code-of-conduct/).
- Added pull request template and issue template 
- References:
- [Issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
- [Pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [Pull request template](https://github.com/wandb/wandb/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml)
- [Pull request and issue template](https://axolo.co/blog/p/part-3-github-pull-request-template)
- [Emoji in …
> Add Code of Conduct

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Some dummy description
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, refactor, chore, test, docs) :information_desk_person: :scroll:
This is a test PR<br>
* **Fixes** :wrench: # (issue)
* **Checklist** :page_with_curl:
* Please delete the content that are not relevant.
> Doc: change image size

- src/main/java/iudx/apd/acl/server/authentication/AuthenticationVerticle.java
- src/main/java/iudx/apd/acl/server/authentication/Constants.java
JWT Leeway added in Authentication Verticle
> jwt-leeway added-1.0.1

- src/main/java/iudx/apd/acl/server/authentication/AuthenticationVerticle.java
- src/main/java/iudx/apd/acl/server/authentication/Constants.java
JWT Leeway time added in Authentication Verticle
> jwt-leeway

- .github/workflows/update_wiki.yml
Describe the changes <br>
* **Fixes** :wrench: # (issue)
* Please delete the content that is not relevant.
> Refactor: GitHub actions

- .github/workflows/update_wiki.yml
Describe the changes <br>
* **Fixes** :wrench: # (issue)
* Please delete the content that is not relevant.
> Refactor file

- .github/workflows/update_wiki.yml
Describe the changes <br>
* **Fixes** :wrench: # (issue)
* Please delete the content that is not relevant.
> Changing image reference

- .github/workflows/docker-image-stable.yml
- .github/workflows/docker-image.yml
- Jenkinsfile
Separated the docker image tag workflow file 
https://github.com/datakaveri/iudx-deployment/issues/721
> Separated the docker image tag workflow file

- src/main/java/iudx/apd/acl/server/apiserver/ApiServerVerticle.java
- src/main/java/iudx/apd/acl/server/authentication/handler/AuthHandler.java
- src/main/java/iudx/apd/acl/server/authentication/handler/UserAccessHandler.java
- src/main/java/iudx/apd/acl/server/authentication/handler/ValidateAccessHandler.java
- src/main/java/iudx/apd/acl/server/authentication/handler/VerifyAuthHandler.java
_refactor_
Reused failure handler to throw error response in authentication and authorization handler classes, removed the dependency of user table to access user information and called auth server instead to get user information each time any API call is made, usedd handlers for authentication and authorization
> Refactor:Authentication, authorization

- src/main/java/iudx/apd/acl/server/notification/CreateNotification.java
- src/main/java/iudx/apd/acl/server/notification/NotificationVerticle.java
- src/main/java/iudx/apd/acl/server/notification/UpdateNotification.java
- src/test/java/iudx/apd/acl/server/notification/TestUpdateNotifications.java
_refactor_
- Refactored update notification class to not call user_table and call DX Auth Server instead
- Removed provider insertion into user_table to stop storing the user information in the database
> Remove user table dependency

- pom.xml
_refactor_
Replaced exec.mainClass with exec.mainClassDev
<br>
> Refactor: Update pom.xml

- .github/workflows/update_wiki.yml
- CODE_OF_CONDUCT.md
- SECURITY.md
- docs/openapi.yaml
Updated version from 1.0.1 to 1.0.2 and updated the support email from support@iudx.org.in to support@datakaveri.org
> Refactor: Update version

- docker-compose.test.yml
This pull request contains the following changes:
- Modified docker-compose.test.yml
> Modified docker-compose.test.yml [Acl-Apd]

- src/main/java/iudx/apd/acl/server/common/RoutingContextHelper.java
Link : https://github.com/orgs/datakaveri/projects/64/views/1?sliceBy%5Bvalue%5D=shreelakshmijoshi&pane=issue&itemId=105693112
> Refactor: fix token return

- src/main/java/iudx/apd/acl/server/authentication/Constants.java
> Hot fix: add schema

- Jenkinsfile
- docker-compose.test.yml
Updated jenkins file && docker compose file for 5.6.0 version
> DI-5 : [5.6.0]  [Jenkins CI] updated jenkins file for 5.6.0 && docker compose file

- src/main/java/iudx/apd/acl/server/authentication/AuthHandler.java
> bearer token
